[changelog]
header = "# Changelog\n\nAll notable changes to stratix will be documented in this file.\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }}))
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^docs", group = "<!-- 2 -->Documentation" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
  { message = "^refactor", group = "<!-- 4 -->Refactor" },
  { message = "^style", group = "<!-- 5 -->Styling" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^ci", group = "<!-- 7 -->CI" },
  { message = "^chore", group = "<!-- 8 -->Miscellaneous Tasks" },
]
protect_breaking_commit_prefix = "BREAKING CHANGE:"
filter_commits = false
tag_pattern = "v[0-9]*"
